/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VideoRouteImport } from './routes/video'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as BoothRouteImport } from './routes/booth'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PrintStripIdRouteImport } from './routes/print.$stripId'
import { Route as EventEventIdRouteImport } from './routes/event.$eventId'
import { Route as EditStripIdRouteImport } from './routes/edit.$stripId'
import { Route as BoothFilmRouteImport } from './routes/booth.film'

const VideoRoute = VideoRouteImport.update({
  id: '/video',
  path: '/video',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const BoothRoute = BoothRouteImport.update({
  id: '/booth',
  path: '/booth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrintStripIdRoute = PrintStripIdRouteImport.update({
  id: '/print/$stripId',
  path: '/print/$stripId',
  getParentRoute: () => rootRouteImport,
} as any)
const EventEventIdRoute = EventEventIdRouteImport.update({
  id: '/event/$eventId',
  path: '/event/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)
const EditStripIdRoute = EditStripIdRouteImport.update({
  id: '/edit/$stripId',
  path: '/edit/$stripId',
  getParentRoute: () => rootRouteImport,
} as any)
const BoothFilmRoute = BoothFilmRouteImport.update({
  id: '/film',
  path: '/film',
  getParentRoute: () => BoothRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/booth': typeof BoothRouteWithChildren
  '/gallery': typeof GalleryRoute
  '/tools': typeof ToolsRoute
  '/video': typeof VideoRoute
  '/booth/film': typeof BoothFilmRoute
  '/edit/$stripId': typeof EditStripIdRoute
  '/event/$eventId': typeof EventEventIdRoute
  '/print/$stripId': typeof PrintStripIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/booth': typeof BoothRouteWithChildren
  '/gallery': typeof GalleryRoute
  '/tools': typeof ToolsRoute
  '/video': typeof VideoRoute
  '/booth/film': typeof BoothFilmRoute
  '/edit/$stripId': typeof EditStripIdRoute
  '/event/$eventId': typeof EventEventIdRoute
  '/print/$stripId': typeof PrintStripIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/booth': typeof BoothRouteWithChildren
  '/gallery': typeof GalleryRoute
  '/tools': typeof ToolsRoute
  '/video': typeof VideoRoute
  '/booth/film': typeof BoothFilmRoute
  '/edit/$stripId': typeof EditStripIdRoute
  '/event/$eventId': typeof EventEventIdRoute
  '/print/$stripId': typeof PrintStripIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/admin'
    | '/auth'
    | '/booth'
    | '/gallery'
    | '/tools'
    | '/video'
    | '/booth/film'
    | '/edit/$stripId'
    | '/event/$eventId'
    | '/print/$stripId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/admin'
    | '/auth'
    | '/booth'
    | '/gallery'
    | '/tools'
    | '/video'
    | '/booth/film'
    | '/edit/$stripId'
    | '/event/$eventId'
    | '/print/$stripId'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/admin'
    | '/auth'
    | '/booth'
    | '/gallery'
    | '/tools'
    | '/video'
    | '/booth/film'
    | '/edit/$stripId'
    | '/event/$eventId'
    | '/print/$stripId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  BoothRoute: typeof BoothRouteWithChildren
  GalleryRoute: typeof GalleryRoute
  ToolsRoute: typeof ToolsRoute
  VideoRoute: typeof VideoRoute
  EditStripIdRoute: typeof EditStripIdRoute
  EventEventIdRoute: typeof EventEventIdRoute
  PrintStripIdRoute: typeof PrintStripIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/video': {
      id: '/video'
      path: '/video'
      fullPath: '/video'
      preLoaderRoute: typeof VideoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booth': {
      id: '/booth'
      path: '/booth'
      fullPath: '/booth'
      preLoaderRoute: typeof BoothRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/print/$stripId': {
      id: '/print/$stripId'
      path: '/print/$stripId'
      fullPath: '/print/$stripId'
      preLoaderRoute: typeof PrintStripIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/event/$eventId': {
      id: '/event/$eventId'
      path: '/event/$eventId'
      fullPath: '/event/$eventId'
      preLoaderRoute: typeof EventEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edit/$stripId': {
      id: '/edit/$stripId'
      path: '/edit/$stripId'
      fullPath: '/edit/$stripId'
      preLoaderRoute: typeof EditStripIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booth/film': {
      id: '/booth/film'
      path: '/film'
      fullPath: '/booth/film'
      preLoaderRoute: typeof BoothFilmRouteImport
      parentRoute: typeof BoothRoute
    }
  }
}

interface BoothRouteChildren {
  BoothFilmRoute: typeof BoothFilmRoute
}

const BoothRouteChildren: BoothRouteChildren = {
  BoothFilmRoute: BoothFilmRoute,
}

const BoothRouteWithChildren = BoothRoute._addFileChildren(BoothRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  BoothRoute: BoothRouteWithChildren,
  GalleryRoute: GalleryRoute,
  ToolsRoute: ToolsRoute,
  VideoRoute: VideoRoute,
  EditStripIdRoute: EditStripIdRoute,
  EventEventIdRoute: EventEventIdRoute,
  PrintStripIdRoute: PrintStripIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
